// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMEJglazCoZ_vip9qtGQcvQwE4Cw7eTKo',
    appId: '1:633286660277:web:a2afe81be2f75eb8e5aefc',
    messagingSenderId: '633286660277',
    projectId: 'test-firebase-d6bed',
    authDomain: 'test-firebase-d6bed.firebaseapp.com',
    storageBucket: 'test-firebase-d6bed.firebasestorage.app',
    measurementId: 'G-8M57HX33NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9V4D_dWuaIcGphLHpPaoVsrct_aBarfs',
    appId: '1:633286660277:android:8e0e03ce9f6ef190e5aefc',
    messagingSenderId: '633286660277',
    projectId: 'test-firebase-d6bed',
    storageBucket: 'test-firebase-d6bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgHdOjehxnaC8hdjEeRmcaHCZg-7fldLw',
    appId: '1:633286660277:ios:723f3daed1332307e5aefc',
    messagingSenderId: '633286660277',
    projectId: 'test-firebase-d6bed',
    storageBucket: 'test-firebase-d6bed.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgHdOjehxnaC8hdjEeRmcaHCZg-7fldLw',
    appId: '1:633286660277:ios:723f3daed1332307e5aefc',
    messagingSenderId: '633286660277',
    projectId: 'test-firebase-d6bed',
    storageBucket: 'test-firebase-d6bed.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMEJglazCoZ_vip9qtGQcvQwE4Cw7eTKo',
    appId: '1:633286660277:web:63fedf42f9eb6c80e5aefc',
    messagingSenderId: '633286660277',
    projectId: 'test-firebase-d6bed',
    authDomain: 'test-firebase-d6bed.firebaseapp.com',
    storageBucket: 'test-firebase-d6bed.firebasestorage.app',
    measurementId: 'G-LCSFS31Q0W',
  );
}
